require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClassroomTeachersController do

  # This should return the minimal set of attributes required to create a valid
  # ClassroomTeacher. As you add validations to ClassroomTeacher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "classroom_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClassroomTeachersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all classroom_teachers as @classroom_teachers" do
      classroom_teacher = ClassroomTeacher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:classroom_teachers).should eq([classroom_teacher])
    end
  end

  describe "GET show" do
    it "assigns the requested classroom_teacher as @classroom_teacher" do
      classroom_teacher = ClassroomTeacher.create! valid_attributes
      get :show, {:id => classroom_teacher.to_param}, valid_session
      assigns(:classroom_teacher).should eq(classroom_teacher)
    end
  end

  describe "GET new" do
    it "assigns a new classroom_teacher as @classroom_teacher" do
      get :new, {}, valid_session
      assigns(:classroom_teacher).should be_a_new(ClassroomTeacher)
    end
  end

  describe "GET edit" do
    it "assigns the requested classroom_teacher as @classroom_teacher" do
      classroom_teacher = ClassroomTeacher.create! valid_attributes
      get :edit, {:id => classroom_teacher.to_param}, valid_session
      assigns(:classroom_teacher).should eq(classroom_teacher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClassroomTeacher" do
        expect {
          post :create, {:classroom_teacher => valid_attributes}, valid_session
        }.to change(ClassroomTeacher, :count).by(1)
      end

      it "assigns a newly created classroom_teacher as @classroom_teacher" do
        post :create, {:classroom_teacher => valid_attributes}, valid_session
        assigns(:classroom_teacher).should be_a(ClassroomTeacher)
        assigns(:classroom_teacher).should be_persisted
      end

      it "redirects to the created classroom_teacher" do
        post :create, {:classroom_teacher => valid_attributes}, valid_session
        response.should redirect_to(ClassroomTeacher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved classroom_teacher as @classroom_teacher" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassroomTeacher.any_instance.stub(:save).and_return(false)
        post :create, {:classroom_teacher => { "classroom_id" => "invalid value" }}, valid_session
        assigns(:classroom_teacher).should be_a_new(ClassroomTeacher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClassroomTeacher.any_instance.stub(:save).and_return(false)
        post :create, {:classroom_teacher => { "classroom_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested classroom_teacher" do
        classroom_teacher = ClassroomTeacher.create! valid_attributes
        # Assuming there are no other classroom_teachers in the database, this
        # specifies that the ClassroomTeacher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClassroomTeacher.any_instance.should_receive(:update_attributes).with({ "classroom_id" => "1" })
        put :update, {:id => classroom_teacher.to_param, :classroom_teacher => { "classroom_id" => "1" }}, valid_session
      end

      it "assigns the requested classroom_teacher as @classroom_teacher" do
        classroom_teacher = ClassroomTeacher.create! valid_attributes
        put :update, {:id => classroom_teacher.to_param, :classroom_teacher => valid_attributes}, valid_session
        assigns(:classroom_teacher).should eq(classroom_teacher)
      end

      it "redirects to the classroom_teacher" do
        classroom_teacher = ClassroomTeacher.create! valid_attributes
        put :update, {:id => classroom_teacher.to_param, :classroom_teacher => valid_attributes}, valid_session
        response.should redirect_to(classroom_teacher)
      end
    end

    describe "with invalid params" do
      it "assigns the classroom_teacher as @classroom_teacher" do
        classroom_teacher = ClassroomTeacher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassroomTeacher.any_instance.stub(:save).and_return(false)
        put :update, {:id => classroom_teacher.to_param, :classroom_teacher => { "classroom_id" => "invalid value" }}, valid_session
        assigns(:classroom_teacher).should eq(classroom_teacher)
      end

      it "re-renders the 'edit' template" do
        classroom_teacher = ClassroomTeacher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClassroomTeacher.any_instance.stub(:save).and_return(false)
        put :update, {:id => classroom_teacher.to_param, :classroom_teacher => { "classroom_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested classroom_teacher" do
      classroom_teacher = ClassroomTeacher.create! valid_attributes
      expect {
        delete :destroy, {:id => classroom_teacher.to_param}, valid_session
      }.to change(ClassroomTeacher, :count).by(-1)
    end

    it "redirects to the classroom_teachers list" do
      classroom_teacher = ClassroomTeacher.create! valid_attributes
      delete :destroy, {:id => classroom_teacher.to_param}, valid_session
      response.should redirect_to(classroom_teachers_url)
    end
  end

end
