require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomProblemsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomProblem. As you add validations to CustomProblem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all custom_problems as @custom_problems" do
      custom_problem = CustomProblem.create! valid_attributes
      get :index
      assigns(:custom_problems).should eq([custom_problem])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_problem as @custom_problem" do
      custom_problem = CustomProblem.create! valid_attributes
      get :show, :id => custom_problem.id
      assigns(:custom_problem).should eq(custom_problem)
    end
  end

  describe "GET new" do
    it "assigns a new custom_problem as @custom_problem" do
      get :new
      assigns(:custom_problem).should be_a_new(CustomProblem)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_problem as @custom_problem" do
      custom_problem = CustomProblem.create! valid_attributes
      get :edit, :id => custom_problem.id
      assigns(:custom_problem).should eq(custom_problem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomProblem" do
        expect {
          post :create, :custom_problem => valid_attributes
        }.to change(CustomProblem, :count).by(1)
      end

      it "assigns a newly created custom_problem as @custom_problem" do
        post :create, :custom_problem => valid_attributes
        assigns(:custom_problem).should be_a(CustomProblem)
        assigns(:custom_problem).should be_persisted
      end

      it "redirects to the created custom_problem" do
        post :create, :custom_problem => valid_attributes
        response.should redirect_to(CustomProblem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_problem as @custom_problem" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProblem.any_instance.stub(:save).and_return(false)
        post :create, :custom_problem => {}
        assigns(:custom_problem).should be_a_new(CustomProblem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProblem.any_instance.stub(:save).and_return(false)
        post :create, :custom_problem => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_problem" do
        custom_problem = CustomProblem.create! valid_attributes
        # Assuming there are no other custom_problems in the database, this
        # specifies that the CustomProblem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomProblem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => custom_problem.id, :custom_problem => {'these' => 'params'}
      end

      it "assigns the requested custom_problem as @custom_problem" do
        custom_problem = CustomProblem.create! valid_attributes
        put :update, :id => custom_problem.id, :custom_problem => valid_attributes
        assigns(:custom_problem).should eq(custom_problem)
      end

      it "redirects to the custom_problem" do
        custom_problem = CustomProblem.create! valid_attributes
        put :update, :id => custom_problem.id, :custom_problem => valid_attributes
        response.should redirect_to(custom_problem)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_problem as @custom_problem" do
        custom_problem = CustomProblem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProblem.any_instance.stub(:save).and_return(false)
        put :update, :id => custom_problem.id, :custom_problem => {}
        assigns(:custom_problem).should eq(custom_problem)
      end

      it "re-renders the 'edit' template" do
        custom_problem = CustomProblem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProblem.any_instance.stub(:save).and_return(false)
        put :update, :id => custom_problem.id, :custom_problem => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_problem" do
      custom_problem = CustomProblem.create! valid_attributes
      expect {
        delete :destroy, :id => custom_problem.id
      }.to change(CustomProblem, :count).by(-1)
    end

    it "redirects to the custom_problems list" do
      custom_problem = CustomProblem.create! valid_attributes
      delete :destroy, :id => custom_problem.id
      response.should redirect_to(custom_problems_url)
    end
  end

end
