require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProblemanswersController do

  # This should return the minimal set of attributes required to create a valid
  # Problemanswer. As you add validations to Problemanswer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all problemanswers as @problemanswers" do
      problemanswer = Problemanswer.create! valid_attributes
      get :index
      assigns(:problemanswers).should eq([problemanswer])
    end
  end

  describe "GET show" do
    it "assigns the requested problemanswer as @problemanswer" do
      problemanswer = Problemanswer.create! valid_attributes
      get :show, :id => problemanswer.id.to_s
      assigns(:problemanswer).should eq(problemanswer)
    end
  end

  describe "GET new" do
    it "assigns a new problemanswer as @problemanswer" do
      get :new
      assigns(:problemanswer).should be_a_new(Problemanswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested problemanswer as @problemanswer" do
      problemanswer = Problemanswer.create! valid_attributes
      get :edit, :id => problemanswer.id.to_s
      assigns(:problemanswer).should eq(problemanswer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Problemanswer" do
        expect {
          post :create, :problemanswer => valid_attributes
        }.to change(Problemanswer, :count).by(1)
      end

      it "assigns a newly created problemanswer as @problemanswer" do
        post :create, :problemanswer => valid_attributes
        assigns(:problemanswer).should be_a(Problemanswer)
        assigns(:problemanswer).should be_persisted
      end

      it "redirects to the created problemanswer" do
        post :create, :problemanswer => valid_attributes
        response.should redirect_to(Problemanswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved problemanswer as @problemanswer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Problemanswer.any_instance.stub(:save).and_return(false)
        post :create, :problemanswer => {}
        assigns(:problemanswer).should be_a_new(Problemanswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Problemanswer.any_instance.stub(:save).and_return(false)
        post :create, :problemanswer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested problemanswer" do
        problemanswer = Problemanswer.create! valid_attributes
        # Assuming there are no other problemanswers in the database, this
        # specifies that the Problemanswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Problemanswer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => problemanswer.id, :problemanswer => {'these' => 'params'}
      end

      it "assigns the requested problemanswer as @problemanswer" do
        problemanswer = Problemanswer.create! valid_attributes
        put :update, :id => problemanswer.id, :problemanswer => valid_attributes
        assigns(:problemanswer).should eq(problemanswer)
      end

      it "redirects to the problemanswer" do
        problemanswer = Problemanswer.create! valid_attributes
        put :update, :id => problemanswer.id, :problemanswer => valid_attributes
        response.should redirect_to(problemanswer)
      end
    end

    describe "with invalid params" do
      it "assigns the problemanswer as @problemanswer" do
        problemanswer = Problemanswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Problemanswer.any_instance.stub(:save).and_return(false)
        put :update, :id => problemanswer.id.to_s, :problemanswer => {}
        assigns(:problemanswer).should eq(problemanswer)
      end

      it "re-renders the 'edit' template" do
        problemanswer = Problemanswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Problemanswer.any_instance.stub(:save).and_return(false)
        put :update, :id => problemanswer.id.to_s, :problemanswer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested problemanswer" do
      problemanswer = Problemanswer.create! valid_attributes
      expect {
        delete :destroy, :id => problemanswer.id.to_s
      }.to change(Problemanswer, :count).by(-1)
    end

    it "redirects to the problemanswers list" do
      problemanswer = Problemanswer.create! valid_attributes
      delete :destroy, :id => problemanswer.id.to_s
      response.should redirect_to(problemanswers_url)
    end
  end

end
